name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pipenv
        run: curl https://raw.githubusercontent.com/kennethreitz/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install
      - name: Run tests
        run: pytest
