name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install pipenv && pipenv install
      - name: Run tests
        run: pytest
