name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Run tests
        run: pytest
