name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lock Pipfile dependencies in requirements.txt
      run: python -m pip install --upgrade pip && pip install pipenv && pipenv lock -r > ./requirements.txt && pipenv lock -r -d > ./requirements-dev.txt
    - name: Install dependencies
      run: pip install -r ./requirements.txt && pip install -r ./requirements-dev.txt
    - name: Run tests
      run: pytest
  build-and-deploy:
    name: Deploy the project
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Serverless framework
      run: npm install -g serverless
    - name: Install Serverless plugins
      run: npm install
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: serverless deploy
